spec:
  source: git://github.com/PraneelUJ/CS_203_Lab9#refs/heads/main
  conda: ''
  origin_url: git://github.com/PraneelUJ/CS_203_Lab9#refs/heads/main
  desired_state: online
  functions:
  - url: Data_prep.py
    name: load-cancer-data
    kind: job
    image: mlrun/mlrun
  - url: Trainer.py
    name: trainer
    kind: job
    image: mlrun/mlrun
  - url: serving.py
    name: serving
    kind: serving
    image: mlrun/mlrun
kind: project
metadata:
  name: sttai-lab9-jovyan
  created: '2025-04-12T13:24:40.049000'
status:
  state: online
